esp_toml_version = 1.0
firmware_images_url = "https://github.com/espzav/UVC-Camera-and-MSC-LVGL-Example/releases/download/camera_example_latest/"

supported_apps = ["UVC_CAMERA_EXAMPLE"]

[UVC_CAMERA_EXAMPLE]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "camera_example_esp32s3.bin"
android_app_url = ""
ios_app_url = ""